### ISSUE TITLE
Linux builds should look for .so files in /usr/lib.

### ISSUE THREAD

**Issue by chadjoan** [DerelictOrg/DerelictSDL2#28]
On Gentoo, the system's .so files are located in `/usr/lib`.
This is the current situation:
```
derelict.util.exception.SharedLibLoadException@../../../../home/chad/.dub/packages/derelict-util-1.0.2/source/derelict/util/exception.d(35): Failed to load one or more shared libraries:
        libSDL2_ttf.so - libSDL2_ttf.so: cannot open shared object file: No such file or directory
        libSDL2_ttf-2.0.so - libSDL2_ttf-2.0.so: cannot open shared object file: No such file or directory
        libSDL2_ttf-2.0.so.0 - libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory
        /usr/local/lib/libSDL2_ttf-2.0.so - /usr/local/lib/libSDL2_ttf-2.0.so: cannot open shared object file: No such file or directory
        /usr/local/lib/libSDL2_ttf-2.0.so.0 - /usr/local/lib/libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory
```
My system looks like this:
```
$ ls /usr/lib/libSDL_ttf*
/usr/lib/libSDL_ttf-2.0.so.0  /usr/lib/libSDL_ttf-2.0.so.0.10.1  /usr/lib/libSDL_ttf.so
$ ls /usr/local/lib
# ...crickets
```

Ideally, there should be some way for callers to include their own search paths __in addition to__ the paths provided by Derelict.  By default, Derelict should probably use the following search logic for .so files:

1. Look at any paths provided by the caller as arguments to `.load(...)`.
2. Look in `./`
3. Look in `$LD_LIBRARY_PATH` ([Reference](http://stackoverflow.com/questions/4743233/is-usr-local-lib-searched-for-shared-libraries))
4. Look in all directories listed in `/etc/ld.so.conf`
5. Look in a baked-in list of last-ditch fallback options.  Although I'm sure better could be done, my current suggestion would look like this:

    ```
    ~/lib
    /usr/local/lib
    /usr/lib
    ```

Tangent time...
At some level, this is giving me a strong desire to have a standard (default) procedure for finding .so files on Linux/Posix systems for the entire D community.  This is something that should "just work" for application developers and end-users, and it reflects poorly on application developers (and the Linux ecosystem) when users get spurious .so load failures.  I wouldn't be surprised if this is a challenge on some other platforms as well.

Whew, when I look at what I wrote, it seems like a significant amount of work!  Maybe, for now, just adding `/usr/lib` (and maybe `~/lib`) to some of the `enum libNames = ...` lines in a few .d files would be a good idea for some easy gratification ;)

Thank you for reading, and thank you for keeping Derelict maintained for a truly respectable length of time!

**Comment by aldacron** [comment]
Looking back at this with a bit of perspective, /lib and /usr/lib are already on the system search path for every Linux distro I've used, so the default libnames that have no path prefix should just work for most systems. I do want to keep the list of libnames as short and manageable as possible. As to custom search paths, that's a separate issue, so I'm closing this for now.  If it's actually a common thing for /usr/lib to be missing from the default search path on certain distros, then anyone can feel free to reopen this and I'll reconsider, but for now I don't think it's worth it to add /usr/lib variants for every package.
