### ISSUE TITLE
Mark functions with @nogc

### ISSUE THREAD

**Issue by Dgame** [DerelictOrg/DerelictSDL2#39]
And add pure & nothrow where possible.

E.g. https://github.com/DerelictOrg/DerelictSDL2/blob/master/source/derelict/sdl2/types.d#L1468

This could be @nogc, pure and nothrow

**Comment by Dgame** [comment]
Further examples:
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source/derelict/sdl2/types.d#L1764
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source/derelict/sdl2/types.d#L1765

**Comment by Dgame** [comment]
https://github.com/DerelictOrg/DerelictSDL2/pull/40

**Comment by Dgame** [comment]
These should be also marked with @nogc: https://github.com/DerelictOrg/DerelictSDL2/blob/master/source/derelict/sdl2/ttf.d#L87

**Comment by Dgame** [comment]
Same for
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source/derelict/sdl2/mixer.d#L122
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source/derelict/sdl2/mixer.d#L127
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source/derelict/sdl2/mixer.d#L131
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source/derelict/sdl2/mixer.d#L135

**Comment by Dgame** [comment]
Nicely done. AFAICS you've only missed one part:
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source/derelict/sdl2/ttf.d#L89

**Comment by aldacron** [comment]
I still have three more branches to apply the changes to before I tag any new releases, so none of the changes are available in DUB yet. I'll get it done sometime in the next 24 hours.

**Comment by Dgame** [comment]
No need to rush

**Comment by Dgame** [comment]
And how does it look? Have you made progress? :)

**Comment by aldacron** [comment]
All done. Everything is tagged and waiting for the dub registry to update.

**Comment by Dgame** [comment]
Sorry, but you forgot a few in functtons.d:
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source%2Fderelict%2Fsdl2%2Ffunctions.d#L551
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source%2Fderelict%2Fsdl2%2Ffunctions.d#L556
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source%2Fderelict%2Fsdl2%2Ffunctions.d#L561
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source%2Fderelict%2Fsdl2%2Ffunctions.d#L566
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source%2Fderelict%2Fsdl2%2Ffunctions.d#L572
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source%2Fderelict%2Fsdl2%2Ffunctions.d#L576

**Comment by Dgame** [comment]
And what is the actual reason to not annotate so many functions as pure? Just curious.

**Comment by aldacron** [comment]
I have no objection to doing so in principle. I just feel that once I start adding pure to one package, then I'll need to go through every package and do the same for consistency. I don't have the time for that. Right now, it isn't really going to make much of a difference so there's no pressing concern to do it. I'll most likely do it eventually.
