### ISSUE TITLE
Mark functions with @nogc - Part 2

### ISSUE THREAD

**Issue by Dgame** [DerelictOrg/DerelictSDL2#41]
It seems that your forgot a few in functions.d:
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source%2Fderelict%2Fsdl2%2Ffunctions.d#L551
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source%2Fderelict%2Fsdl2%2Ffunctions.d#L556
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source%2Fderelict%2Fsdl2%2Ffunctions.d#L561
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source%2Fderelict%2Fsdl2%2Ffunctions.d#L566
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source%2Fderelict%2Fsdl2%2Ffunctions.d#L572
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source%2Fderelict%2Fsdl2%2Ffunctions.d#L576

**Comment by aldacron** [comment]
Thanks! I hope I've gotten everything covered now :)
