### ISSUE TITLE
Wrong signature of SDL_JoystickUpdate

### ISSUE THREAD

**Issue by Dgame** [DerelictOrg/DerelictSDL2#44]
SDL_JoystickUpdate takes no parameters:

http://hg.libsdl.org/SDL/file/default/include/SDL_joystick.h#l164
https://github.com/DerelictOrg/DerelictSDL2/blob/master/source/derelict/sdl2/functions.d#L213

**Comment by Dgame** [comment]
I've Opened PR #45

**Comment by Dgame** [comment]
@aldacron Can we merge this soon? It's only a minor but IMO important API fix.

**Comment by aldacron** [comment]
Sorry, I've been extremely busy with another project that's taking most of my free time and I haven't been keeping up with this. I don't want to hold up your release of DGame! I need to apply the fix to every branch and then tag a new release for each. It's easier for me to do that from home, and I'm at my hot dog shop right now. So I'll get to it in a few hours.

**Comment by Dgame** [comment]
All right. I did not know that it is so much work. Excuse me for the rush. :) Can I help you somehow?
