### ISSUE TITLE
Remove (s|u)int\d+ types ?

### ISSUE THREAD

**Issue by Temtaime** [DerelictOrg/DerelictSDL2#46]
Hi ! I just wonder why there's sint16 ... etc types ?
It is actually in C, where type sizes are not defined. In D size of each type is strongly defined, so i think we can use uint / short / ... types, can't we ?

**Comment by aldacron** [comment]
Every Derelict binding is a direct translation of the C headers to D. Any code using those types on the C side can be ported to D without worrying about changing the types. Often, you can just copy-paste C code into your D modules. For your own code, you can use whatever you want. I use the D types myself when working with SDL, but I won't be removing the aliases from Derelict.
