### ISSUE TITLE
Add support for new SDL 2.0.4

### ISSUE THREAD

**Issue by jcd** [DerelictOrg/DerelictSDL2#49]

**Comment by aldacron** [comment]
Support for SDL 2.0.4 was added in the 1.9.5 tag (the latest on that branch is 1.9.7), so you can use it now. See [this blog post](http://dblog.aldacron.net/2015/04/support-for-sdl-2-0-4-in-derelict/) for details on how to enable it. I just need to make sure that nothing in the final release of 2.0.4 is missing in the binding, then I'll tag a 2.0 release. I'm on vacation in the States right now. I'll be back home on my dev box in a few days and take care of the release then.
