### ISSUE TITLE
SDL_LockTexture crash

### ISSUE THREAD

**Issue by thisdyingsoul** [DerelictOrg/DerelictSDL2#50]
I´m trying a simple SDL app and it crash when calling SDL_LockTexture.

SDL_LockTexture(null, null,null, null); don´t crash.

But if I put the texture on first argument or any other combination of arguments, the app crash;

**Comment by aldacron** [comment]
The issues page here is for reporting actual problems with Derelict or enhancement requests. It is not a place to come for help debugging your code. That's what the D Forums are for. Once you have verified a Derelict bug, then come here and post it.

That said, I'll help you out in this thread if I can, but you've not provided enough info for anyone to do anything but guess. Make sure you are checking return codes on every SDL function you are calling that can fail. From your description, it sounds like you might have a null texture, meaning it wasn't loaded properly. If you want more help than that, please post a reproducible minimal example of the problem.

**Comment by aldacron** [comment]
Since I haven't heard anything else from you on this, I'm closing the issue. Please reopen if you need to.
