### ISSUE TITLE
SDL_GetEventFilter Regression

### ISSUE THREAD

**Issue by pineapplemachine** [DerelictOrg/DerelictSDL2#57]
Somehow the change made here is no longer present in master, which is causing compile issues with mach: https://github.com/DerelictOrg/DerelictSDL2/commit/8a281a4f4bae9ff9e42e4e907b7d456cba2bec44#diff-fa3c41fb49bcd5e2c7e65a92ed31d758

**Comment by mdparker** [comment]
OK, this is now fixed in 2.1.1. Sorry again for the delay. Thanks!
