### ISSUE TITLE
The first parameter of SDL_GetDisplayUsableBounds is wrong

### ISSUE THREAD

**Issue by DDoS** [DerelictOrg/DerelictSDL2#60]
It should be an [int](https://github.com/spurious/SDL-mirror/blob/master/include/SDL_video.h#L338).

But the binding wrongly specifies [SDL_DisplayMode*](https://github.com/DerelictOrg/DerelictSDL2/blob/master/source/derelict/sdl2/functions.d#L500).

A hack fix for now is to pass the int as a pointer. Might not work since the data types don't necessarily have the same size.

**Comment by mdparker** [comment]
Thanks for reporting it. Fixed in both 2.1.2 and 3.0.0-alpha.4.
