### ISSUE TITLE
SDL_EnclosePoints wrong return type

### ISSUE THREAD

**Issue by radcapricorn** [DerelictOrg/DerelictSDL2#62]
Declared in functions.d:
```D
alias da_SDL_EnclosePoints = void function(const(SDL_Point)*,int,const(SDL_Rect)*,SDL_Rect*);
```

but that function [should be returning SDL_bool](https://wiki.libsdl.org/SDL_EnclosePoints).
[Origin](https://forum.dlang.org/thread/woxtpjdwohqphyquafoj@forum.dlang.org).

**Comment by mdparker** [comment]
Fixed in 2.1.4 and 3.0.0-alpha.6. Thanks!
