### ISSUE TITLE
SDL functions seemingly no-ops when built in Release (on OSX)

### ISSUE THREAD

**Issue by sasq64** [DerelictOrg/DerelictSDL2#67]
On OSX, SDL2 suddenly started to fail in _Release_ mode seemingly by silently failing and turning all SDL calls into no-ops ?

This minimal example:
```
    SDL_Window *window;
    SDL_Renderer *renderer;
    DerelictSDL2.load();
    enforce(SDL_Init(SDL_INIT_VIDEO) >= 0, "Failed to initialize SDL: " ~ to!string(SDL_GetError()));
    assert(SDL_CreateWindowAndRenderer(640, 480, 0, &window, &renderer) == 0);
    writeln(window, " ", renderer);
```
prints `null null` when built using `dub -b release` but works fine with `dub -b debug`

**Comment by mdparker** [comment]
I'll see if I can reproduce this on my MacBook Pro, but I'll need a day or two before I can get to it. Just wanted to let you know I'm not ignoring you in case it takes me longer.

**Comment by sasq64** [comment]
That was quick.
I actually worked around this by using separate CreateWindow and CreateRenderer calls, so it seems it's just `SDL_CreateWindowAndRenderer` that behaves weirdly

**Comment by mdparker** [comment]
Actually, looking at your snippet again, I'm sure it's the fact that you wrapped the function call in an `assert`. That would be ignored when compiling in release mode, so that the function call never takes place.

**Comment by sasq64** [comment]
DUH! Now I feel pretty stupid... Thanks for your time anyway.
