### ISSUE TITLE
SDL_BLENDOPERATIONSDL_BLENDOPERATION_ADD

### ISSUE THREAD

**Issue by Barugon** [DerelictOrg/DerelictSDL2#68]
https://github.com/DerelictOrg/DerelictSDL2/blob/b3dbde7ef1bb0068dfad9810e3e9e23109ab6e26/source/derelict/sdl2/internal/sdl_types.d#L236

Should be just SDL_BLENDOPERATION_ADD.

**Comment by mdparker** [comment]
Thanks. Fixed in 3.1.0-alpha.2.
